#Toolchain Variable

TARGET=arm

CC="/home/reeeemk/server_security/cross-compilateur/opt/Boardcon/4.3.3/bin/arm-linux-gcc -mcpu=arm920t -mtune=arm920t -march=armv4t"
AR=/home/reeeemk/server_security/cross-compilateur/opt/Boardcon/4.3.3/bin/arm-linux-ar
RANLIB=/home/reeeemk/server_security/cross-compilateur/opt/Boardcon/4.3.3/bin/arm-linux-ranlib
STRIP=/home/reeeemk/server_security/cross-compilateur/opt/Boardcon/4.3.3/bin/arm-linux-strip
OBJDUMP=/home/reeeemk/server_security/cross-compilateur/opt/Boardcon/4.3.3/bin/arm-linux-objdump

LIB_DIR_HOST=/home/reeeemk/server_security/cross-compilateur/opt/Boardcon/4.3.3/arm-none-linux-gnueabi/libc/lib

RELEASEDIR=/home/reeeemk/server_security/tools/package
ZLIB_PATH_ARM=/home/reeeemk/server_security/tools/package/zlib-package
SSL_PATH_ARM=/home/reeeemk/server_security/tools/package/ssl-package/usr/local/ssl